#cloud-config
#package_upgrade: true

packages:
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libffi-dev
  - liblzma-dev
  - tk-dev
  - uuid-dev
  - xz-utils
  - fail2ban
  - ufw
