#cloud-config

users:
  - name: ansible
    groups: users, wheel, docker
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOTH7wfLQu4O0RBAukHj4XKCRw9xsi9RKitieEZuADwT ansible@lynx

runcmd:
  - su - ansible -c "curl https://pyenv.run | bash"
  - su - ansible -c "echo 'export PATH=\"\$HOME/.pyenv/bin:\$PATH\"' >> ~/.bashrc"
  - su - ansible -c "echo 'eval \"\$(pyenv init --path)\"' >> ~/.bashrc"
  - su - ansible -c "echo 'eval \"\$(pyenv init -)\"' >> ~/.bashrc"
  - su - ansible -c "echo 'eval \"\$(pyenv virtualenv-init -)\"' >> ~/.bashrc"
  - su - ansible -c "bash -c 'source ~/.bashrc && ~/.pyenv/bin/pyenv install 3.13'"
  - su - ansible -c "bash -c 'source ~/.bashrc && ~/.pyenv/bin/pyenv global 3.13'"
  - su - ansible -c "bash -c 'pip install --upgrade pip'"
  - su - ansible -c "bash -c 'pip install ansible'"